name: Build with Gradle

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs
